# Generated by Django 2.1.2 on 2018-10-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma_Controle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data do Relatório')),
                ('data_ref', models.DateTimeField(verbose_name='Data de Referência')),
                ('atualizado_em', models.DateTimeField(null=True, verbose_name='Data da Atualização')),
                ('fechamento', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'GRT_tb_cronograma_controle',
            },
        ),
        migrations.CreateModel(
            name='Tabela_Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_relatorio', models.CharField(max_length=150)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'GRT_tb_relatorios',
            },
        ),
        migrations.CreateModel(
            name='Tabela_Trilha_Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.IntegerField(default=1)),
                ('fk_idrelatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GerenciadordeRotinas.Tabela_Relatorios')),
            ],
            options={
                'db_table': 'GRT_tb_trilha_relatorio',
            },
        ),
        migrations.CreateModel(
            name='Tabela_Trilhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trilha', models.CharField(max_length=150)),
                ('plataforma', models.CharField(max_length=50)),
                ('codtrilha_legado', models.IntegerField(default=0, null=True)),
                ('ativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'GRT_tb_trilhas',
            },
        ),
        migrations.AddField(
            model_name='tabela_trilha_relatorio',
            name='fk_idtrilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GerenciadordeRotinas.Tabela_Trilhas'),
        ),
        migrations.AddField(
            model_name='cronograma_controle',
            name='fk_idtrilharelatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GerenciadordeRotinas.Tabela_Trilha_Relatorio'),
        ),
    ]
