# Generated by Django 2.1.2 on 2018-10-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GerenciadordeRotinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_relatorios',
            name='criado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Criação'),
        ),
        migrations.AddField(
            model_name='tabela_relatorios',
            name='modificao_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Modificação'),
        ),
        migrations.AlterField(
            model_name='tabela_relatorios',
            name='nome_relatorio',
            field=models.CharField(max_length=150, verbose_name='Nome Relatório'),
        ),
    ]
