# Generated by Django 2.1.2 on 2018-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GerenciadordeRotinas', '0002_auto_20181017_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela_relatorios',
            name='modificao_em',
            field=models.DateTimeField(null=True, verbose_name='Data Modificação'),
        ),
    ]
